version: '3.8'

services:
  postgres:
    image: postgres # You can specify any version you prefer
    container_name: unimart_db
    environment:
      POSTGRES_USER: gray  # Set your desired username
      POSTGRES_PASSWORD: falcon568  # Set your desired password
      POSTGRES_DB: unimart  # Set your desired database name
    ports:
      - "4005:5432"  # Maps port 5432 on the host to port 5432 in the container
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data to avoid losing it when the container stops

volumes:
  postgres_data:
    driver: local
